name: mayo-reddit-tipbot
channels:
  - defaults
dependencies:
  - python=3.7
  - pandas=0.25
  - requests
  - pip
  - pip:
      - praw
      - qrcode==6.1
      - click
      - black
      - pytest
      - peewee
      - pymysql
      - psycopg2-binary
      - pylint
      - nanopy
      - bitstring
      - stellar-sdk

